# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-15T07:58:13+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AwareDatetime, BaseModel, ConfigDict
from typing_extensions import Literal


class Parent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: str
    block_id: Optional[str] = None
    page_id: Optional[str] = None


class CreatedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object: Literal['user']
    id: str


class LastEditedBy(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    object: Literal['user']
    id: str


class Type(Enum):
    paragraph = 'paragraph'
    to_do = 'to_do'
    bulleted_list_item = 'bulleted_list_item'
    numbered_list_item = 'numbered_list_item'
    code = 'code'
    column = 'column'
    column_list = 'column_list'
    divider = 'divider'
    equation = 'equation'
    heading_1 = 'heading_1'
    heading_2 = 'heading_2'
    heading_3 = 'heading_3'
    image = 'image'
    quote = 'quote'
    equation_1 = 'equation'
    table = 'table'
    table_row = 'table_row'
    toggle = 'toggle'


class Child(BaseModel):
    type: Type


class ColumnBlock(BaseModel):
    object: Literal['block']
    id: str
    parent: Optional[Parent] = None
    type: str
    created_time: AwareDatetime
    created_by: Optional[CreatedBy] = None
    last_edited_time: Optional[AwareDatetime] = None
    last_edited_by: Optional[LastEditedBy] = None
    archived: bool
    in_trash: Optional[bool] = None
    has_children: bool
    metadata: Optional[Dict[str, Any]] = None
    column: Dict[str, Any]
    children: List[Child]
