# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-20T15:49:35+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from jsondoc.models.block.base import BlockBase
from jsondoc.models.block.types.rich_text.base import RichTextBase
from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal


class Type(Enum):
    external = 'external'
    file = 'file'


class Image(BaseModel):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Type
    caption: Optional[List[RichTextBase]] = None


class ImageBlock(BlockBase):
    dummy: Optional[str] = None
    type: Literal['image']
    image: Image
