# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-06T15:48:03+00:00

from __future__ import annotations

from jsondoc.models.block.base import BlockBase
from jsondoc.models.file.base import FileBase
from pydantic import ConfigDict
from typing_extensions import Literal


class ImageBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal['image'] = 'image'
    image: FileBase
