# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase
from jsondoc.models.block.types.table_row import TableRowBlock


class Table(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    table_width: Optional[int] = None
    has_column_header: bool
    has_row_header: bool


class TableBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal["table"] = "table"
    table: Table
    children: Optional[List[TableRowBlock]] = None
