name: Build and Test

on:
  push:
    branches: [main]
    paths:
      - "typescript/**"
  pull_request:
    branches: [main]
    paths:
      - "typescript/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./typescript

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./typescript/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        run: npm run generate-types

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
