# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-08T10:03:42+00:00

from __future__ import annotations

from pydantic import BaseModel


class FileBase(BaseModel):
    pass
