# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-05T14:27:19+00:00

from __future__ import annotations

from pydantic import BaseModel


class FileBase(BaseModel):
    pass
