# generated by datamodel-codegen:
#   filename:  unordered_list_schema.json
#   timestamp: 2024-12-19T10:00:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase


class UnorderedList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=True,
    )


class UnorderedListBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal["unordered_list"] = "unordered_list"
    unordered_list: UnorderedList
    children: Optional[List[BlockBase]] = None