# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from pydantic import ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase
from jsondoc.models.file.base import FileBase


class ImageBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal["image"] = "image"
    image: FileBase
