# generated by datamodel-codegen:
#   filename:  ordered_list_schema.json
#   timestamp: 2024-12-19T10:00:00+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase


class OrderedList(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=True,
    )


class OrderedListBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal["ordered_list"] = "ordered_list"
    ordered_list: OrderedList
    children: Optional[List[BlockBase]] = None