# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-15T07:20:03+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Type(Enum):
    paragraph = 'paragraph'
    to_do = 'to_do'
    bulleted_list_item = 'bulleted_list_item'
    numbered_list_item = 'numbered_list_item'
    code = 'code'
    column = 'column'
    column_list = 'column_list'
    divider = 'divider'
    equation = 'equation'
    heading_1 = 'heading_1'
    heading_2 = 'heading_2'
    heading_3 = 'heading_3'
    image = 'image'
    quote = 'quote'
    equation_1 = 'equation'
    table = 'table'
    table_row = 'table_row'
    toggle = 'toggle'


class Model(BaseModel):
    type: Type
