# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase


class Equation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expression: str


class EquationBlock(BlockBase):
    type: Literal["equation"] = "equation"
    equation: Equation
