# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from typing import Any, Dict

from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase


class DividerBlock(BlockBase):
    type: Literal["divider"] = "divider"
    divider: Dict[str, Any]
