# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from pydantic import BaseModel


class FileBase(BaseModel):
    pass
