# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-10T15:45:21+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal

from jsondoc.models.block.base import BlockBase
from jsondoc.models.block.types.rich_text.base import RichTextBase
from jsondoc.models.shared_definitions import Color


class NumberedListItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
        arbitrary_types_allowed=True,
    )
    rich_text: Optional[List[RichTextBase]] = []
    color: Optional[Color] = None


class NumberedListItemBlock(BlockBase):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    type: Literal["numbered_list_item"] = "numbered_list_item"
    numbered_list_item: NumberedListItem
    children: Optional[List[BlockBase]] = None
