# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-20T16:21:12+00:00

from __future__ import annotations

from typing import List, Optional

from jsondoc.models.block.base import BlockBase
from jsondoc.models.block.types.rich_text.base import RichTextBase
from jsondoc.models.shared_definitions import Color
from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal


class Quote(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        arbitrary_types_allowed=True,
    )
    rich_text: List[RichTextBase]
    color: Optional[Color] = None
    children: Optional[List[BlockBase]] = None


class QuoteBlock(BlockBase):
    type: Literal['quote']
    quote: Quote
