# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-06T15:48:03+00:00

from __future__ import annotations

from jsondoc.models.block.base import BlockBase
from pydantic import BaseModel, ConfigDict
from typing_extensions import Literal


class Equation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    expression: str


class EquationBlock(BlockBase):
    type: Literal['equation'] = 'equation'
    equation: Equation
