name: Build and Test

on:
  push:
    branches: [main]
    paths:
      - "ts/**"
  pull_request:
    branches: [main]
    paths:
      - "ts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: ./ts/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate types
        run: npm run generate-types

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
