# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-20T16:58:38+00:00

from __future__ import annotations

from typing import Any, Dict

from jsondoc.models.block.base import BlockBase
from typing_extensions import Literal


class DividerBlock(BlockBase):
    type: Literal['divider']
    divider: Dict[str, Any]
