# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-05T14:27:19+00:00

from __future__ import annotations

from typing import List, Optional

from jsondoc.models.block.types.rich_text.base import RichTextBase
from jsondoc.models.file.external import FileExternal
from pydantic import ConfigDict


class ExternalImage(FileExternal):
    model_config = ConfigDict(
        arbitrary_types_allowed=True,
    )
    caption: Optional[List[RichTextBase]] = None
