# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-09-04T22:43:27+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel


class Type(Enum):
    external = 'external'
    file = 'file'


class Model(BaseModel):
    type: Type
