# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-20T16:30:59+00:00

from __future__ import annotations

from pydantic import BaseModel


class RichTextBase(BaseModel):
    pass
