# generated by datamodel-codegen:
#   filename:  example.json
#   timestamp: 2024-08-21T08:03:24+00:00

from __future__ import annotations

from pydantic import BaseModel


class RichTextBase(BaseModel):
    pass
