# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-cache: true
          cache-dependency-glob: "python/requirements.txt"

      - name: Install dependencies
        working-directory: ./python
        run: |
          if [ -f requirements.txt ]; then uv pip install -r requirements.txt; fi
          uv pip install pytest

      - name: Install the package
        working-directory: ./python
        run: |
          uv pip install .

      - name: Test with pytest
        working-directory: ./python
        run: |
          PYTHONPATH=.. uv run pytest

      - name: Check if the main script is installed
        working-directory: ./python
        run: |
          uv run convert_jsondoc --help

  build-typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./typescript
        run: npm ci

      - name: Generate types
        working-directory: ./typescript
        run: npm run generate-types

      - name: Build
        working-directory: ./typescript
        run: npm run build

      - name: Run tests
        working-directory: ./typescript
        run: npm test

      - name: Check linting
        working-directory: ./typescript
        run: npm run lint
